# Generated by Django 4.2 on 2023-04-22 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='api_id',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
