# Generated by Django 4.2 on 2023-04-22 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_game_api_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite_game',
            name='game',
        ),
        migrations.AddField(
            model_name='favorite_game',
            name='game_api_id',
            field=models.IntegerField(default=0),
        ),
    ]
