# Generated by Django 4.2 on 2023-04-22 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_remove_favorite_game_game_favorite_game_game_api_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='minumum_system_requirements',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='screenshots',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='video_play_back',
            field=models.URLField(blank=True, null=True),
        ),
    ]
