# Generated by Django 4.2 on 2023-04-22 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_alter_game_minumum_system_requirements_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite_game',
            name='game_api_id',
        ),
        migrations.AddField(
            model_name='favorite_game',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='favorite_games', to='games.game'),
        ),
    ]
