# Generated by Django 4.2 on 2023-04-24 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_remove_favorite_game_game_api_id_favorite_game_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite_game',
            name='status',
            field=models.CharField(choices=[('played', 'Played'), ('play_later', 'Play Later'), ('currently_playing', 'Currently Playing')], max_length=50),
        ),
    ]
