# Generated by Django 4.2 on 2023-04-25 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_alter_favorite_game_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite_game',
            old_name='status',
            new_name='my_status',
        ),
    ]
