# Generated by Django 4.2 on 2023-04-25 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_rename_my_status_favorite_game_my_game_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='minumum_system_requirements',
            new_name='minimum_system_requirements',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='release_Date',
            new_name='release_date',
        ),
    ]
