# Generated by Django 4.2 on 2023-04-22 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='game',
        ),
        migrations.AddField(
            model_name='rating',
            name='game_api_id',
            field=models.IntegerField(default=0),
        ),
    ]
