# Generated by Django 4.2 on 2023-04-22 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0003_remove_rating_game_rating_game_api_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='content',
        ),
    ]
