# Generated by Django 4.2 on 2023-04-28 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='random_profile_pic',
            field=models.TextField(blank=True, null=True),
        ),
    ]
